version: '3.4'

services:
  db:
    image: mysql
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_db
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
  dockerexpressapp:
    image: dockerexpressapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
volumes: 
  my-db: